export const ADMIN_PLACEHOLDER_FIELDS = {
    hero: [
        "title",
        "subtitle",
        "primaryCtaLabel",
        "primaryCtaHref",
        "secondaryCtaLabel",
        "secondaryCtaHref",
        "imageUrl",
    ],
    inventoryCards: [
        "title",
        "propertyUse",
        "propertyType",
        "businessType",
        "zone",
        "priceExample",
        "terrainM2Example",
        "constructionM2Example",
        "imageUrl",
    ],
    inventoryFilters: [
        "searchPlaceholder",
        "businessTypes",
        "propertyUses",
        "sortLabels",
        "emptyStateTitle",
        "emptyStateCopy",
    ],
    contact: [
        "phone",
        "email",
        "addressLines",
        "hours",
        "formIntroCopy",
        "privacyCopy",
        "successMessage",
    ],
} as const;
